# Generated by Django 4.2.1 on 2023-06-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('image', models.ImageField(blank=True, upload_to='users_images/%Y/%m/%d')),
                ('archive', models.FileField(blank=True, upload_to='user_archives/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'База пользовательских данных',
                'verbose_name_plural': 'База пользовательских данных',
                'ordering': ['name'],
            },
        ),
    ]
