# Generated by Django 4.2.1 on 2023-06-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_data_bgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='bgcolor',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='Цвет фона'),
        ),
    ]
